[config]
schemaVersion = "0.0.1"

[package]
namespace = "skytech6"
name = "CrimsonMoon"
versionNumber = "1.0.0"
description = "A sacraficial alter to praise the moon! Honor it in return for a blood moon!"
websiteUrl = "https://github.com/CrimsonMods/CrimsonMoon/"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_V_Rising = "1.691.3"
deca-Bloodstone = "0.2.2"

[build]
icon = "./images/logo_256.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./dist"
target = ""

[publish]
communities = ["v-rising"]
repository = "https://thunderstore.io"
[publish.categories]
v-rising = ["1.0-update", "mods", "server"]